<a href="https://colab.research.google.com/github/adinovitarini/LinAlgElectricCircuit/blob/main/MeshAnalysiSolution_UsingMatrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

This code was implemented to compute the solution for compute the urrent from OCW MIT Free Course (https://ocw.mit.edu/courses/electrical-engineering-and-computer-science/6-071j-introduction-to-electronics-signals-and-measurement-spring-2006/lecture-notes/nodal_mesh_methd.pdf) page 16 and 17

In [ ]:
import numpy as np 

In [ ]:
A = np.array([[5,-2],[-2,3]])
B = np.linalg.det(A)
print("determinant of matrix A is : ",B)
y = np.array([[6],[3]])
x = np.linalg.inv(A)
print("Inverse matrix A is : \n",x)
X = np.zeros((2,1))
for i in range(len(x)):
  for j in range(len(y[1])):
    for k in range(len(y)):
      X[i][j] += x[i][k]*y[k][j]
print("Solution is : \n",X)
current1 = X[0]
current3 = X[1]
current2 = current3-current1
print('I1 = ',current1,'A')
print('I2 = ',current2,'A')
print('I3 = ',current3,'A')

determinant of matrix A is :  11.000000000000002
Inverse matrix A is : 
 [[0.27272727 0.18181818]
 [0.18181818 0.45454545]]
Solution is : 
 [[2.18181818]
 [2.45454545]]
I1 =  [2.18181818] A
I2 =  [0.27272727] A
I3 =  [2.45454545] A


In [ ]:
A = np.array([[10,-4,0],[-4,6,-2],[0,-2,4]])
B = np.linalg.det(A)
print("determinant of matrix A is : ",B)
y = np.array([[12],[-6],[2]])
x = np.linalg.inv(A)
print("Inverse matrix A is : \n",x)
X = np.zeros((len(y),1))
for i in range(len(x)):
  for j in range(len(y[1])):
    for k in range(len(y)):
      X[i][j] += x[i][k]*y[k][j]
print("Solution is : \n",X)
current1 = X[0]
current3 = X[1]
current5 = X[2]
current2 = current3-current1
current4 = current5-current3
print('I1 = ',current1,'A')
print('I2 = ',current2,'A')
print('I3 = ',current3,'A')
print('I4 = ',current4,'A')
print('I5 = ',current5,'A')

determinant of matrix A is :  136.00000000000006
Inverse matrix A is : 
 [[0.14705882 0.11764706 0.05882353]
 [0.11764706 0.29411765 0.14705882]
 [0.05882353 0.14705882 0.32352941]]
Solution is : 
 [[ 1.17647059]
 [-0.05882353]
 [ 0.47058824]]
I1 =  [1.17647059] A
I2 =  [-1.23529412] A
I3 =  [-0.05882353] A
I4 =  [0.52941176] A
I5 =  [0.47058824] A
